version: "3.7"
services:

  # Server PHP
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./docker-compose/php
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-network

  # Database
  db:    
    image: postgres
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
       - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel-network

  # Webserver
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-network

  # Interface for database
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    ports:
      - "6543:80"
    networks:
      - laravel-network

# Persistind Data
volumes:
  postgres-data:
   driver: local

networks:
  laravel-network:
    driver: bridge

  